### ISSUE TITLE
Issues In Step 2 - Apply-PnPProvisioning Template

### ISSUE THREAD

**Issue by hturbano** [SharePoint/sp-dev-modernization#1]
I keep getting issues in Step 2 after setting up the Azure apps.  Any suggestions? I have double checked and gone through all the steps multiple times. Help would be greatly appreciated.
[https://drive.google.com/file/d/1MPCWUsOxsYkepjtBRyOlFHWrnC0AgA73/view?usp=sharing](url)

**Comment by hturbano** [comment]
![applypnp](https://user-images.githubusercontent.com/2497090/49186663-de62e800-f32a-11e8-86d9-688a08defc8c.PNG)

**Comment by b00johst** [comment]
Hi,
I'm facing the same issue. The error seems to occur when processing the WebApiPermissions handler or directly after. I have double checked every step in the guide but I can’t find any errors in my setup. The app registration exists with the correct name and permissions. The permissions have been given consent. Does anyone have any ideas on that the issue may be?

![applytenanttemplate](https://user-images.githubusercontent.com/12508433/49378732-9f0f0f80-f70d-11e8-8baa-bcc0c5bb855e.png)

**Comment by hturbano** [comment]
Yes, you are correct. It happens with processing the WebApiPermissions. I have also double checked and believe I have all the other steps created properly. I tried reverting PnpPowerShell back to previous versions to see if that would work, but the ApplyTenant command wasn't available in the others. If you happen to come across a solution, Please let me know. Trying to convert some classic team sites to the new modern ones and this would be a godsend. 
Thanks!

**Comment by b00johst** [comment]
I created a regular PnPProvisioningTemplate and copied the <pnp:Templates ID="SP-DEV-MODERNIZATION-TEMPLATES"></pnp:Templates> to the new template and applied it with Apply-PnPProvisioningTemplate. After adding the StorageEntityProperties manually everything worked as expected. 

I still don’t know why I can’t run Apply-PnPTenantTemplate but I guess there are some kind of error when creating the storageEntityProperties or creating the site collection. This issue seems more related to pnp powershell than sp-dev-modernization.

**Comment by jansenbe** [comment]
@hturbano, @b00johst,

When we created this tenant template we did fix the provisioning engine (waiting for app install, check for async provisioning readiness, a new token for "everyoneexceptexternals")...which implies that you'll need to self-service compile sites core and PowerShell to make it work currently. That's why the docs mention PnP PS December version or higher. 

If you didn't build your own PS version and if you can't wait for the December drop (Monday next week latest) then check this article: https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/manual%20setup/modernization-ui-manual-sharepoint.old.md. It contains more details about how the SharePoint site has been set up.

Also note that the December version of PnP PS will have a new cmdlet to for modernizing a page: `ConvertTo-PnPClientSidePage -Identity page.aspx -Overwrite` which might help as well.

About the missing `Apply-PnPTenantTemplate`: in earlier PS versions this was called `Apply-PnPProvisioningHierarchy`

**Comment by jansenbe** [comment]
@hturbano , @b00johst : if you still have issues getting the tool setup then let me know. I can free up some time for a Skype/Teams session to help you get unblocked.

**Comment by jansenbe** [comment]
Hi @hturbano , @b00johst,

Wanted to let you know that the December 2018 release of PS is out + we've finalized the script to install the Azure side. See https://github.com/SharePoint/sp-dev-modernization/blob/master/Solutions/PageTransformationUI/docs/deploymentguide.md. Also see our monthly community call recording in which I demo the setup: https://youtu.be/NppqtPo4-bo?t=1622.

Let me if you're both up and running so that I can close the call.

**Comment by jansenbe** [comment]
Hi @hturbano , @b00johst, 

I'm closing this issue as there's no further feedback. Feel free to re-open it or create a new one if you still have pending asks.
