### ISSUE TITLE
Transform slow when processing WikiImages

### ISSUE THREAD

**Issue by pkbullock** [SharePoint/sp-dev-modernization#111]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

Performance

#### Observed Behavior

During transformation, there is roughly a 3 minute lag between transform of Web Part field to Wiki Image. See snippet from Markdown report, this maybe network conditions but want to raise to check if there is a condition that would cause significant delay. 

This delay is per page.

#### Steps to Reproduce

Two Web Part fields of type image using the WikiImage - transform.

#### Extra Detail

Snippet from Markdown Report shows a 3 minute jump between these actions.

Date | Operation | Actions Performed
-- | -- | --
11/04/2019 14:23:39 | Web Part Mapping | Web   Part:'XXXImageField' of type 'SharePointPnP.Modernization.WikiImagePart' is   being transformed
11/04/2019 14:27:22 | Adding Web Parts to   Target Page | Using 'Image' modern   web part

**Comment by pkbullock** [comment]
To Me - update: between _Processing selector functions_ and _Combining mapping data_ is the area to focus performance testing

**Comment by jansenbe** [comment]
Hi @pkbullock,

Thx for reporting this. Did you see this slowness when using PS or from .Net...reason for the ask is that I see sometimes, random, delays via PS at the end. The page is ready and exists but seems like the last step (publish?) sometimes takes a long time. 

Alternative thinking is around the "asset transfer"...does the test portal have a complex site structure? You've added code to find the correct web for an asset and that code does iterate over all the webs ==> we should probably cache that so that the iteration only happens once for the first asset in the transformation session. 

Thoughts?

**Comment by pkbullock** [comment]
Hi @jansenbe - this will be the first place I will look, the subsite structure is around 1000. I knew that code was smelly 😒 should have listened to my instincts.

**Comment by jansenbe** [comment]
Closing as #125 was merged
