### ISSUE TITLE
Modernization UI problem with tables mapping

### ISSUE THREAD

**Issue by hildedepauw** [SharePoint/sp-dev-modernization#215]
#### Category

[ ] Bug

#### Problem Area

[ ] Page Transformation: Page is not looking correct after transformation (from PowerShell)

#### Expected or Desired Behavior

situation : migration of table with 2 cells. 1st cell contains image (red exclamation mark) , 2nd cell contains text.
Expected behavior : I expected after migration same representation

#### Observed Behavior

After migration, the 1st cell gives the image with some error text *  *, and replicates the same image underneath the table

#### Steps to Reproduce
- classic site page or wiki page. With table of 2 cells (1st cell contains image, 2nd cell contains text.) 
- migration of page with the PowerShell method

![migrationTableModernPage](https://user-images.githubusercontent.com/13408081/62202062-db703980-b388-11e9-9dfa-efc23dc9cfe2.png)

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hey @hildedepauw,

In the modern text editor you cannot insert/edit images inside a table, hence the transformation tech will add the image as separate image web part on the page so that you can still give it a place on the page. 

To make it visible where the image lived a place holder text is shown + we leave the image html tag in the modern text html...nowadays the editor does retain the image tag and thus shows the image, but you cannot edit the image. You can however drag the separate image web part again in the table to add it back if needed.

Going forward these are options you could today apply :
- Option 1: keep using the table with the image inside, remove the place holder text and separate image web part
- Option 2: if the tables are used for layout purposes it's better to create for example a 2 column section and drag the web part image in column and add the text in the other

Going forward I'll change the default behaviour of the transformation to be like above explained option 1...the current behavior was there because in the past the image got dropped from the editor on save, currently that's not the case anymore so "option 1" makes sense as default. This is something I'll add for the August release.

Hope this clarifies things and provides you with a path forward.

**Comment by jansenbe** [comment]
You can actually already now remove the placeholder text above the image by updating the web part mapping file of the SharePoint.Modernization.WikiTextPart web part:

From:
```XML
Functions="{UsePlaceHolders} = ReturnTrue(); {CleanedText} = TextCleanup({Text},{UsePlaceHolders})"
```
To:
```XML
Functions="{UsePlaceHolders} = ReturnFalse(); {CleanedText} = TextCleanup({Text},{UsePlaceHolders})"
```
The "to" situation will be the new default for next release.

**Comment by jansenbe** [comment]
Needed changes are implemented, as of the September release the defaults will result in only the image embedded in the table, no place holder and no extra image web part. You can always change the webpartmapping.xml if you want the placeholder text and use the new AddTableListImageAsImageWebPart flag to trigger the add of the extra image web part. 

Will close this issue, but don't hesitate to reach out in case you've issues with this.
