### ISSUE TITLE
Content editor webpart migration

### ISSUE THREAD

**Issue by BenJ74** [SharePoint/sp-dev-modernization#23]
Hi,

I just noticed that the "ConvertTo-PnPClientSidePage" cmdlet doesn't migrate content coming from "content editor" webparts.

Is there a way to map those contents to "Text" webparts in the modern experience?

Thanks.

**Comment by jansenbe** [comment]
Hi @BenJ74 ,

The default behavior of page transformation is to only transform to 1st party (so OOB) web parts and there's no modern script editor or content editor web part. This, however, does not mean that you can't use a 3rd party (custom) alternative. Follow below steps to enable the conversion of content editor and script editor web parts:

- Install the open source script editor web part (https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor) to your tenant
- The `ConvertTo-ClientSidePage` cmdlet has a built-in default webpartmapping.xml file, in order to use the custom script editor web part deployed in the previous step you need to provide an updated mapping file: 
  - You can grab a default version from https://github.com/SharePoint/sp-dev-modernization/blob/master/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Nuget/webpartmapping.xml
  - Then uncomment the mapping for script editor, content editor and html form web part (lines 193, 204, 521). The default webpartmapping already contains the needed mapping for using the custom script editor, but since that web part is not installed by default the mapping is commented out
- In the final step you now use the `-WebpartMapping` parameter to specify the location of your "custom" mapping file

Above steps should get you unblocked, if not then please let me know.

**Comment by jansenbe** [comment]
Hi @BenJ74,

Did the above help?

**Comment by jansenbe** [comment]
Thanks @BenJ74. Will close this issue now
