### ISSUE TITLE
Feature request - wiki page/webpart page metadata copy across site collections

### ISSUE THREAD

**Issue by gautamdsheth** [SharePoint/sp-dev-modernization#253]
#### Category

[ ] Bug
[x] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[x] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

It should be allowed to copy metadata for wiki pages when doing transformation across site collections/tenants.

#### Observed Behavior

Currently, not able to copy metadata for wiki pages when doing transformation across site collections.

The page is correctly transformed and have no issues or errors, however the metadata for these pages is not copied over.

#### Steps to Reproduce

Please let me know if I could be missing something quite simple or might have completely missed something.

I am using the below code in SPO. Both the source and destination site are in SPO and same tenant:

```csharp

string siteUrl = "https://tenant.sharepoint.com/sites/SourceWikiSite/";
string userName = "user";
AuthenticationManager am = new AuthenticationManager();
using (var cc = am.GetSharePointOnlineAuthenticatedContextTenant(siteUrl, userName, "password"))
{
	var targetContext = cc.Clone("https://tenant.sharepoint.com/sites/DestSite");
	
	var pageFile = cc.Web.GetFileByServerRelativeUrl("/sites/SourceWikiSite/SitePages/wikipage101.aspx");
	cc.Load(pageFile, p => p.ListItemAllFields);
	cc.ExecuteQuery();

	var page = pageFile.ListItemAllFields;
	
	PageTransformator pageTransformator = new PageTransformator(cc, targetContext);

	PageTransformationInformation pti = new PageTransformationInformation(page)
	{
		HandleWikiImagesAndVideos = true,
		Overwrite = true,
		SkipTelemetry = true,
		AddTableListImageAsImageWebPart = true,
		CopyPageMetadata = true,
	};

	try
	{
		Console.WriteLine($"Transforming page {page.FieldValues["FileLeafRef"]}");

		pageTransformator.Transform(pti);
	}
	catch (ArgumentException ex)
	{
		Console.WriteLine($"Page {page.FieldValues["FileLeafRef"]} could not be transformed: {ex.Message}");
	}
}			
```
I am using the latest dev version of the Modernization framework. 

Looks like [here](https://github.com/SharePoint/sp-dev-modernization/blob/ac427af797559ab53bd27b2e74f3d9aa574d1b08/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Transform/PageTransformator.cs#L731), we are checking that if it has targetcontext, we wont copy metadata. 

If this is indeed not supported at the moment, I would be happy to contribute a PR for the same. Would love discuss the approach for the same, though i guess something similar to what we are doing for Publishing pages would be good enough.

**Comment by jansenbe** [comment]
Hey @gautamdsheth ,

Currently this indeed is not possible for wiki/webpart pages, we only support metadata copy for in-place transformations as that point all the fields are always available since we stay in the same library. 

If you've time for a PR on this then I'm supporting that:
- Let's assume the needed fields are available on the target sitepages library - for publishing pages we do have advanced features like field and content type mapping, but that's overkill for wiki pages...let's keep wiki page transformation as simple as possible
- If the CopyPageMetadata flag is set and if the same field exists in the target sitepages library then the field contents can be copied over assuming the field does not have references to assets that are only available in the source site collection (e.g. local term set)
- When a field is not copied we should output a log message so that it's clear which fields are skipped and why

Happy to further elaborate on this if you want, just let me know. If you want this in the September release time is short, the PR should be in by Friday this week, but targeting the October release is also fine...I'm already more than happy that you want to spent some time on this.

**Comment by gautamdsheth** [comment]
Hey @jansenbe , thanks for the reply :) . Totally makes sense to keep it simple. Will target the October release and follow the approach that you mentioned here. Happy to contribute :)

**Comment by jansenbe** [comment]
@gautamdsheth : do you still think you get this feature done for the October release? Don't want to push you, but we need this capability for October. You've already helped us a lot via a ton of PR's, if you've no available time for this then I totally understand that and I'll spent time on this myself.

**Comment by gautamdsheth** [comment]
Hey @jansenbe, sure am working on it. Will send a PR sometime in this week. Is that fine? Kinda got distracted because of other PRs

**Comment by jansenbe** [comment]
Thanks for this work @gautamdsheth ! I've just tested and merged your PR, so closing this issue now
