### ISSUE TITLE
Error for page with Script Editor

### ISSUE THREAD

**Issue by Kokila106** [SharePoint/sp-dev-modernization#26]
I have  webpart page with Script Editor webpart

When transforming the webpart page to modern page it displays below message
'Busy generating a modern version of WebPartPage4.aspx...
Error: Object reference not set to an instance of an object.'

**Comment by jansenbe** [comment]
Hi @Kokila106,

I assume you're testing with the transformation service? If so that one has the default webpartmapping.xml file that does not include the mapping for the script editor web part.  Below instructions show how to use an updated webpartmapping file. Would be good if you could also test from PowerShell or .Net to see if you get an error? Normally there should be no error, the script editor will simply be skipped.

**Instructions for updating the webpartmapping file for PowerShell usage**

Follow below steps to enable the conversion of content editor and script editor web parts:

- Install the open source script editor web part (https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor) to your tenant
- The ConvertTo-ClientSidePage cmdlet has a built-in default webpartmapping.xml file, in order to use the custom script editor web part deployed in the previous step you need to provide an updated mapping file:
  - You can grab a default version from https://github.com/SharePoint/sp-dev-modernization/blob/master/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Nuget/webpartmapping.xml
  - Then uncomment the mapping for script editor, content editor and html form web part (lines 193, 204, 521). The default webpartmapping already contains the needed mapping for using the custom script editor, but since that web part is not installed by default the mapping is commented out
In the final step you now use the -WebpartMapping parameter to specify the location of your "custom" mapping file

**Instructions for updating the webpartmapping file for Transformation service usage**
The easiest way to deploy the Azure Function app binaries is by using Kudu:

- Go Azure provisioning Function App
- Click on Platform features and select Advanced tools (Kudu) from the Development Tools section
- Drag the updated webpartmapping.xml file inside the wwwroot folder pane

**Comment by jansenbe** [comment]
Hi @Kokila106,

Did you manage to update the webpartmapping.xml file in the service?

**Comment by jansenbe** [comment]
Hi @Kokila106,

I've moved the information about how to configure for script editor usage into the FAQ: https://github.com/SharePoint/sp-dev-modernization/blob/pagetransformationuibeta/Solutions/PageTransformationUI/docs/modernization-ui-faq.md.

Will close this issue now.
