### ISSUE TITLE
Choice fields are not copied correctly (from on-prem to online)

### ISSUE THREAD

**Issue by jansenbe** [SharePoint/sp-dev-modernization#266]
See last comments in #253 for the details. Seems like choice fields are not handled correctly during publishing page transform from on-prem to online

**Comment by jansenbe** [comment]
Hi @KVSolutions, In my testing I can copy choice fields from on-prem to online and also from online to online without any issue. Tested with the September release. Can you cross check you have configured the fields correctly in your page layout mapping file?

**Comment by gautamdsheth** [comment]
hey @jansenbe , i was kinda able to reproduce this issue. This boils down to the field being present in the list but not in the content type. In this scenario, even though the mapping is correct, the field will not be copied over because we are checking the content type fields and not list fields here:

https://github.com/SharePoint/sp-dev-modernization/blob/4e46ce50b3352082cc8e12cb4d1d2e035cccfb4c/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Cache/CacheManager.cs#L250-L259

Would suggest that instead of content type fields, we check the fields present in the list. Might be a minor performance hit, but will be more robust while migrating. 

Thoughts ? Happy to submit a PR for the same, in fact already wrote some part of it, but wanted to run by you first :)

**Comment by jansenbe** [comment]
That makes sense, thanks for the additional research here @gautamdsheth . Yes, a PR would be really helpful, looking forward to it :-)

**Comment by jansenbe** [comment]
Thanks for the fix @gautamdsheth !

@KVSolutions: this should fix your issue. Fix will be part of the October release. I'll close this issue now, but if you still see issues when using the October release then please open a new issue.
