### ISSUE TITLE
default.aspx not upgraded

### ISSUE THREAD

**Issue by RajiVenkat242** [SharePoint/sp-dev-modernization#311]
We are using the below command for upgrading a default.aspx page. For few pages alone, we get the below issue. The page has three xsltlistviewwebpart. after the script runs, we could see the modern page in root folder, but it is not valid and not working.

Error:
_Column 'Title' does not exist. It may have been deleted by another user.

Attached the page transformation log & screenshot of the page
[default.aspx - error.txt](https://github.com/SharePoint/sp-dev-modernization/files/3688478/default.aspx.-.error.txt)
![page](https://user-images.githubusercontent.com/54291136/66172184-7971d000-e668-11e9-9f00-792b248d4811.png)

**Comment by RajiVenkat242** [comment]
PnP command: 
ConvertTo-PnPClientSidePage -Identity "default.aspx" -Folder "<root>"

**Comment by jansenbe** [comment]
The error is there because when we save the page it complains about the title field not being available in the sitepages library (https://stackoverflow.com/questions/53620643/cannot-load-title-field-to-modern-team-subsites shows the same symptoms). Some asks:

- Please cross check the sitepages library and ensure it has a title column of type text (
- Do other pages in the same site work or do they fail as well?
- Can you repro this if you try to modernize that same page again (add the -Overwrite flag)?

**Comment by RajiVenkat242** [comment]
i have added the Title column to the site pages library. It worked. Thank you so much for the support.
