### ISSUE TITLE
Transforming content search web parts: extracting result source and search query 

### ISSUE THREAD

**Issue by westerdaled** [SharePoint/sp-dev-modernization#353]
[ ] Bug
[x ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
In our environment we have a number of Content search web part (CSWPs) used in classic publishing pages, with the following criteria.

-  Search against specific Result sources.

-  Use Search query to filter the results against ContentType ID and Taxonomy fields.

- Enable pagination

 

**Transforming CSWPs  to Highlighted Content web part (HCWPs)**

Currently cross site transformation of CSWPs on classic publishing sites is not supported.  This means there is a manual process needed to: 

1. Set the site collection url in the "Selected Sites" as Results Sources is not supported. 

2. Copy the search query from existing Content Search web part. Enter the filter conditions as key-value pair (KQL format) in Custom query.
e.g.
From CSWP Query:
 ```
ContentTypeId:0x01010044FBB32B81DE4447A78F209576C290FA01* 
 owstaxIdRelatedx0020To:{Page.Policy.Name}  
-owstaxIdPolicyx0020Name:"Useful Stuff"

```

To HCWP KQL:
```
(ContentTypeId:0x01010044FBB32B81DE4447A78F209576C290FA01*) 
(owstaxIdPolicyx0020Name:"Community:Sharing is Caring Policy;*") (owstaxIdRelatedx0020To:"Responsibilities and Working:Useful Stuff;")
```

Q: is there a way to automate any the above steps say even,  for a CSWP on a page  located on  non publishing site. 
Q: Will cross site be supported anytime

**Transforming  CSWPs  to community Search Results Web parts**
One option we've started looking at to get around the cross site ban 😑 is to use the search results Web part which does support  result sources and pagination.  
Q: Do we simply create  a new web part mapping entry and go through ["I want to  add an extra web part to page"](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#i-want-to-add-an-extra-web-part-on-the-created-page)
Q: Can we redirect the default mapping to Search Results web part instead of the HCWP using custom page layout file  Again can we still need to extract  the search query and possible transform as appropriate the SRWP:
`<Property Name="DataProviderJSON" Type="string" Functions="ContentBySearchToSearchResultsProperties
`
 - Similarly, we want enable a mapping of Script Editor web part to desired custom web part.  Do we just add the definition of the custom web part added to webpartmapping.xml and the redirection is  made via the custom  page layout mapping file  ?

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi @westerdaled ,

About **Transforming CSWPs to Highlighted Content web part (HCWPs)**

You can mark the CBS, CBQ web parts as cross site collection supported in your web part mapping file by adding the `CrossSiteTransformationSupported` attribute. So 

```xml
<WebPart Type="Microsoft.SharePoint.Publishing.WebControls.ContentByQueryWebPart, Microsoft.SharePoint.Publishing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
```
will become 

```xml
<WebPart Type="Microsoft.SharePoint.Publishing.WebControls.ContentByQueryWebPart, Microsoft.SharePoint.Publishing, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" CrossSiteTransformationSupported="true">
```

Once you do you need to specify this custom webpartmapping.xml file as input for the transformation via the `-WebPartMappingFile` parameter of the `ConvertTo-PnPClientSidePage` cmdlet. 

About **Transforming CSWPs to community Search Results Web parts**

You would have to update the mapping that today is used for the CBS/CBQ web parts. So today CBS looks like this:

```XML
<WebPart Type="Microsoft.Office.Server.Search.WebControls.ContentBySearchWebPart, Microsoft.Office.Server.Search, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
        <Properties>
          <Property Name="BypassResultTypes" Type="bool" Functions="{FullPath} = Concatenate({Host}, {Web});{EncodedWeb} = HtmlEncodeForJson({FullPath})"/>
          <Property Name="ItemTemplateId" Type="string"/>
          ...
          <Property Name="StatesJson" Type="string"/>
          <Property Name="ShowSortOptions" Type="bool"/>
        </Properties>
        <Mappings>
          <Mapping Default="true" Name="default">
            <ClientSideWebPart Type="ContentRollup" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&quot;title&quot;&#58;&quot;{Title}&quot;{SearchablePlainTexts}&#125;,&quot;imageSources&quot;&#58;&#123;{ImageSources}&#125;,&quot;links&quot;&#58;&#123;&quot;baseUrl&quot;&#58;&quot;{EncodedWeb}&quot;{Links}&#125;,&quot;componentDependencies&quot;&#58;&#123;&quot;layoutComponentId&quot;&#58;&quot;cea5863a-b857-46bb-aaf0-ae5f7cb447b6&quot;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;2.4&quot;,&quot;properties&quot;&#58;{JsonProperties}&#125;"/>
          </Mapping>
        </Mappings>
      </WebPart>
```
Where as in your custom mapping it would be something like this:

```XML
<WebPart Type="Microsoft.Office.Server.Search.WebControls.ContentBySearchWebPart, Microsoft.Office.Server.Search, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c">
        <Properties>
          <Property Name="BypassResultTypes" Type="bool" Functions="{FullPath} = Concatenate({Host}, {Web});{EncodedWeb} = HtmlEncodeForJson({FullPath})"/>
          <Property Name="ItemTemplateId" Type="string"/>
          ...
          <Property Name="StatesJson" Type="string"/>
          <Property Name="ShowSortOptions" Type="bool"/>
        </Properties>
        <Mappings>
          <Mapping Default="true" Name="default">
            <ClientSideWebPart Type="Custom" ControlId="<community search web part id>" Order="10" JsonControlData="<community json webpart properties>"/>
          </Mapping>
        </Mappings>
      </WebPart>
```

The link you shared (https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#i-want-to-add-an-extra-web-part-on-the-created-page) shows a similar concept, but than for adding a new web part which will be put on a page via the publishing page layout file. 

While thinking about this I noticed there's an additional complexity: since the HCWP web part properties are so complex they're created via specific function (https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-api#contentbysearchtohighlightedcontentproperties) which returns all data (including the parsed queries) as a JSON blob. This JSON blob only works for HCWP, so in case of using the community search web parts the solution will require a custom function and possibly also a custom property to enable this via switch (see https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-webparts#enabling-the-use-of-the-community-script-editor-web-part-to-be-used-during-transformation).

**Comment by westerdaled** [comment]
@jansenbe  Thank you sir! Timely as we have a series of demos planned over the next couple of weeks for various peeps.

**Comment by jansenbe** [comment]
Doing some housekeeping and closing this one as there's no pending ask.
