### ISSUE TITLE
Classic to Modern Page Migration PNP - Issue

### ISSUE THREAD

**Issue by pkrsingh86** [SharePoint/sp-dev-modernization#39]
Hello @jansenbe  
There are issue in migrating the classic page to modern using .Net based SharePoint PnP Modernization framework.

I get below error. It is random, sometimes i get this error and sometime not. Tried 'Include(WelcomePage)'.Nothing works. Any suggestion please

**Error Description:** 
The property or field 'WelcomePage' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

**Comment by jansenbe** [comment]
Hi @pkrsingh86,

Does this issue still occur when you're using the latest version? Can you share a stacktrace?

**Comment by jansenbe** [comment]
Hi @pkrsingh86 ,

I've looked at the code using WelcomePage and that's only on one spot. What I think is that somehow for your site this property is either not set or not retrievable. I've added an extra check in the code for this so that you're not getting an error (https://github.com/SharePoint/sp-dev-modernization/commit/5ffabb9eeed740fe518dab633915763833605b22).

This fix will be in the February version of the nuget package and PnP PowerShell.

I'll close this issue, for now, feel free to re-open or create a new one if you still have issues after testing with the February release.

**Comment by JasonMichaelRobertson** [comment]
This is still broken for me
