### ISSUE TITLE
Support for SP2019

### ISSUE THREAD

**Issue by nicolas6969** [SharePoint/sp-dev-modernization#5]
Dear Bert,
Would it be possible to offer an on-prem version for SP2019?

Best regards
Nicolas

**Comment by jansenbe** [comment]
Hi @nicolas6969,

Supporting SP2019 makes sense as that would allow in-place modernization scenarios for on-premises customers. This, however, does require a lot of engineering work and will not be possible in the short term but in the long term adding SP2019 will be done. I can't commit to a specific timeline for that right now.

**Comment by nicolas6969** [comment]
Hi @jansenbe,
That's ok, thanks a lot for feedback and picking it up.

Btw. Was a very interesting session last week in Copenhagen.....

**Comment by jansenbe** [comment]
This has been open for a long time and to be honest there's just too much work to realize the SharePoint 2019 support and keep moving it forward, especially given the low demand we've seen for this feature. Due to this I'm going to close this issue. If folks want to realize this then they can start from the current code base and make the needed changes, I'm more than happy to provide some advice.
